networks:
  raft-common-network:
    driver: bridge
    ipam:
      config:
      - subnet: 10.0.0.0/24
      driver: default
services:
  client1:
    build: .
    command:
    - python
    - -m
    - client.run_client
    - --name
    - client1
    container_name: client1
    depends_on:
      node3:
        condition: service_started
    networks:
      raft-common-network:
        ipv4_address: 10.0.0.5
    ports:
    - 5558:8888/udp
  node1:
    build: .
    command:
    - python
    - -m
    - raft.run_node
    - --node
    - 10.0.0.2
    - --cluster
    - node2,node3
    - --name
    - node1
    - --clients
    - client1
    container_name: node1
    environment:
    - NODE=node1
    - CLUSTER=node2,node3
    - CLIENTS=client1
    networks:
      raft-common-network:
        ipv4_address: 10.0.0.2
    ports:
    - 3333:8080/udp
  node2:
    build: .
    command:
    - python
    - -m
    - raft.run_node
    - --node
    - 10.0.0.3
    - --cluster
    - node1,node3
    - --name
    - node2
    - --clients
    - client1
    container_name: node2
    environment:
    - NODE=node2
    - CLUSTER=node1,node3
    - CLIENTS=client1
    networks:
      raft-common-network:
        ipv4_address: 10.0.0.3
    ports:
    - 3334:8080/udp
  node3:
    build: .
    command:
    - python
    - -m
    - raft.run_node
    - --node
    - 10.0.0.4
    - --cluster
    - node1,node2
    - --name
    - node3
    - --clients
    - client1
    container_name: node3
    environment:
    - NODE=node3
    - CLUSTER=node1,node2
    - CLIENTS=client1
    networks:
      raft-common-network:
        ipv4_address: 10.0.0.4
    ports:
    - 3335:8080/udp
version: '3.8'
