networks:
  raft-common-network:
    driver: bridge
    ipam:
      config:
      - subnet: 10.0.0.0/24
      driver: default
services:
  client1:
    build: .
    command:
    - python
    - -m
    - evaluator.run_evaluator
    - --name
    - client1
    - --evaluator
    - cca
    - --duration
    - '7'
    - --requests_per_second
    - '130'
    - --write_ratio
    - '0'
    - --key_range
    - '50'
    container_name: client1
    depends_on:
      node5:
        condition: service_started
    networks:
      raft-common-network:
        ipv4_address: 10.0.0.7
    ports:
    - 5560:8888/udp
    volumes:
    - ./dump:/app/dump
  client10:
    build: .
    command:
    - python
    - -m
    - evaluator.run_evaluator
    - --name
    - client10
    - --evaluator
    - cca
    - --duration
    - '7'
    - --requests_per_second
    - '130'
    - --write_ratio
    - '0'
    - --key_range
    - '50'
    container_name: client10
    depends_on:
      node5:
        condition: service_started
    networks:
      raft-common-network:
        ipv4_address: 10.0.0.16
    ports:
    - 5569:8888/udp
    volumes:
    - ./dump:/app/dump
  client11:
    build: .
    command:
    - python
    - -m
    - evaluator.run_evaluator
    - --name
    - client11
    - --evaluator
    - cca
    - --duration
    - '7'
    - --requests_per_second
    - '130'
    - --write_ratio
    - '0'
    - --key_range
    - '50'
    container_name: client11
    depends_on:
      node5:
        condition: service_started
    networks:
      raft-common-network:
        ipv4_address: 10.0.0.17
    ports:
    - 5570:8888/udp
    volumes:
    - ./dump:/app/dump
  client12:
    build: .
    command:
    - python
    - -m
    - evaluator.run_evaluator
    - --name
    - client12
    - --evaluator
    - cca
    - --duration
    - '7'
    - --requests_per_second
    - '130'
    - --write_ratio
    - '0'
    - --key_range
    - '50'
    container_name: client12
    depends_on:
      node5:
        condition: service_started
    networks:
      raft-common-network:
        ipv4_address: 10.0.0.18
    ports:
    - 5571:8888/udp
    volumes:
    - ./dump:/app/dump
  client13:
    build: .
    command:
    - python
    - -m
    - evaluator.run_evaluator
    - --name
    - client13
    - --evaluator
    - cca
    - --duration
    - '7'
    - --requests_per_second
    - '130'
    - --write_ratio
    - '0'
    - --key_range
    - '50'
    container_name: client13
    depends_on:
      node5:
        condition: service_started
    networks:
      raft-common-network:
        ipv4_address: 10.0.0.19
    ports:
    - 5572:8888/udp
    volumes:
    - ./dump:/app/dump
  client14:
    build: .
    command:
    - python
    - -m
    - evaluator.run_evaluator
    - --name
    - client14
    - --evaluator
    - cca
    - --duration
    - '7'
    - --requests_per_second
    - '130'
    - --write_ratio
    - '0'
    - --key_range
    - '50'
    container_name: client14
    depends_on:
      node5:
        condition: service_started
    networks:
      raft-common-network:
        ipv4_address: 10.0.0.20
    ports:
    - 5573:8888/udp
    volumes:
    - ./dump:/app/dump
  client15:
    build: .
    command:
    - python
    - -m
    - evaluator.run_evaluator
    - --name
    - client15
    - --evaluator
    - cca
    - --duration
    - '7'
    - --requests_per_second
    - '130'
    - --write_ratio
    - '0'
    - --key_range
    - '50'
    container_name: client15
    depends_on:
      node5:
        condition: service_started
    networks:
      raft-common-network:
        ipv4_address: 10.0.0.21
    ports:
    - 5574:8888/udp
    volumes:
    - ./dump:/app/dump
  client16:
    build: .
    command:
    - python
    - -m
    - evaluator.run_evaluator
    - --name
    - client16
    - --evaluator
    - cca
    - --duration
    - '7'
    - --requests_per_second
    - '130'
    - --write_ratio
    - '0'
    - --key_range
    - '50'
    container_name: client16
    depends_on:
      node5:
        condition: service_started
    networks:
      raft-common-network:
        ipv4_address: 10.0.0.22
    ports:
    - 5575:8888/udp
    volumes:
    - ./dump:/app/dump
  client17:
    build: .
    command:
    - python
    - -m
    - evaluator.run_evaluator
    - --name
    - client17
    - --evaluator
    - cca
    - --duration
    - '7'
    - --requests_per_second
    - '130'
    - --write_ratio
    - '0'
    - --key_range
    - '50'
    container_name: client17
    depends_on:
      node5:
        condition: service_started
    networks:
      raft-common-network:
        ipv4_address: 10.0.0.23
    ports:
    - 5576:8888/udp
    volumes:
    - ./dump:/app/dump
  client18:
    build: .
    command:
    - python
    - -m
    - evaluator.run_evaluator
    - --name
    - client18
    - --evaluator
    - cca
    - --duration
    - '7'
    - --requests_per_second
    - '130'
    - --write_ratio
    - '0'
    - --key_range
    - '50'
    container_name: client18
    depends_on:
      node5:
        condition: service_started
    networks:
      raft-common-network:
        ipv4_address: 10.0.0.24
    ports:
    - 5577:8888/udp
    volumes:
    - ./dump:/app/dump
  client19:
    build: .
    command:
    - python
    - -m
    - evaluator.run_evaluator
    - --name
    - client19
    - --evaluator
    - cca
    - --duration
    - '7'
    - --requests_per_second
    - '130'
    - --write_ratio
    - '0'
    - --key_range
    - '50'
    container_name: client19
    depends_on:
      node5:
        condition: service_started
    networks:
      raft-common-network:
        ipv4_address: 10.0.0.25
    ports:
    - 5578:8888/udp
    volumes:
    - ./dump:/app/dump
  client2:
    build: .
    command:
    - python
    - -m
    - evaluator.run_evaluator
    - --name
    - client2
    - --evaluator
    - cca
    - --duration
    - '7'
    - --requests_per_second
    - '130'
    - --write_ratio
    - '0'
    - --key_range
    - '50'
    container_name: client2
    depends_on:
      node5:
        condition: service_started
    networks:
      raft-common-network:
        ipv4_address: 10.0.0.8
    ports:
    - 5561:8888/udp
    volumes:
    - ./dump:/app/dump
  client20:
    build: .
    command:
    - python
    - -m
    - evaluator.run_evaluator
    - --name
    - client20
    - --evaluator
    - cca
    - --duration
    - '7'
    - --requests_per_second
    - '130'
    - --write_ratio
    - '0'
    - --key_range
    - '50'
    container_name: client20
    depends_on:
      node5:
        condition: service_started
    networks:
      raft-common-network:
        ipv4_address: 10.0.0.26
    ports:
    - 5579:8888/udp
    volumes:
    - ./dump:/app/dump
  client21:
    build: .
    command:
    - python
    - -m
    - evaluator.run_evaluator
    - --name
    - client21
    - --evaluator
    - cca
    - --duration
    - '7'
    - --requests_per_second
    - '130'
    - --write_ratio
    - '0'
    - --key_range
    - '50'
    container_name: client21
    depends_on:
      node5:
        condition: service_started
    networks:
      raft-common-network:
        ipv4_address: 10.0.0.27
    ports:
    - 5580:8888/udp
    volumes:
    - ./dump:/app/dump
  client22:
    build: .
    command:
    - python
    - -m
    - evaluator.run_evaluator
    - --name
    - client22
    - --evaluator
    - cca
    - --duration
    - '7'
    - --requests_per_second
    - '130'
    - --write_ratio
    - '0'
    - --key_range
    - '50'
    container_name: client22
    depends_on:
      node5:
        condition: service_started
    networks:
      raft-common-network:
        ipv4_address: 10.0.0.28
    ports:
    - 5581:8888/udp
    volumes:
    - ./dump:/app/dump
  client23:
    build: .
    command:
    - python
    - -m
    - evaluator.run_evaluator
    - --name
    - client23
    - --evaluator
    - cca
    - --duration
    - '7'
    - --requests_per_second
    - '130'
    - --write_ratio
    - '0'
    - --key_range
    - '50'
    container_name: client23
    depends_on:
      node5:
        condition: service_started
    networks:
      raft-common-network:
        ipv4_address: 10.0.0.29
    ports:
    - 5582:8888/udp
    volumes:
    - ./dump:/app/dump
  client24:
    build: .
    command:
    - python
    - -m
    - evaluator.run_evaluator
    - --name
    - client24
    - --evaluator
    - cca
    - --duration
    - '7'
    - --requests_per_second
    - '130'
    - --write_ratio
    - '0'
    - --key_range
    - '50'
    container_name: client24
    depends_on:
      node5:
        condition: service_started
    networks:
      raft-common-network:
        ipv4_address: 10.0.0.30
    ports:
    - 5583:8888/udp
    volumes:
    - ./dump:/app/dump
  client25:
    build: .
    command:
    - python
    - -m
    - evaluator.run_evaluator
    - --name
    - client25
    - --evaluator
    - cca
    - --duration
    - '7'
    - --requests_per_second
    - '130'
    - --write_ratio
    - '0'
    - --key_range
    - '50'
    container_name: client25
    depends_on:
      node5:
        condition: service_started
    networks:
      raft-common-network:
        ipv4_address: 10.0.0.31
    ports:
    - 5584:8888/udp
    volumes:
    - ./dump:/app/dump
  client26:
    build: .
    command:
    - python
    - -m
    - evaluator.run_evaluator
    - --name
    - client26
    - --evaluator
    - cca
    - --duration
    - '7'
    - --requests_per_second
    - '130'
    - --write_ratio
    - '0'
    - --key_range
    - '50'
    container_name: client26
    depends_on:
      node5:
        condition: service_started
    networks:
      raft-common-network:
        ipv4_address: 10.0.0.32
    ports:
    - 5585:8888/udp
    volumes:
    - ./dump:/app/dump
  client27:
    build: .
    command:
    - python
    - -m
    - evaluator.run_evaluator
    - --name
    - client27
    - --evaluator
    - cca
    - --duration
    - '7'
    - --requests_per_second
    - '130'
    - --write_ratio
    - '0'
    - --key_range
    - '50'
    container_name: client27
    depends_on:
      node5:
        condition: service_started
    networks:
      raft-common-network:
        ipv4_address: 10.0.0.33
    ports:
    - 5586:8888/udp
    volumes:
    - ./dump:/app/dump
  client28:
    build: .
    command:
    - python
    - -m
    - evaluator.run_evaluator
    - --name
    - client28
    - --evaluator
    - cca
    - --duration
    - '7'
    - --requests_per_second
    - '130'
    - --write_ratio
    - '0'
    - --key_range
    - '50'
    container_name: client28
    depends_on:
      node5:
        condition: service_started
    networks:
      raft-common-network:
        ipv4_address: 10.0.0.34
    ports:
    - 5587:8888/udp
    volumes:
    - ./dump:/app/dump
  client29:
    build: .
    command:
    - python
    - -m
    - evaluator.run_evaluator
    - --name
    - client29
    - --evaluator
    - cca
    - --duration
    - '7'
    - --requests_per_second
    - '130'
    - --write_ratio
    - '0'
    - --key_range
    - '50'
    container_name: client29
    depends_on:
      node5:
        condition: service_started
    networks:
      raft-common-network:
        ipv4_address: 10.0.0.35
    ports:
    - 5588:8888/udp
    volumes:
    - ./dump:/app/dump
  client3:
    build: .
    command:
    - python
    - -m
    - evaluator.run_evaluator
    - --name
    - client3
    - --evaluator
    - cca
    - --duration
    - '7'
    - --requests_per_second
    - '130'
    - --write_ratio
    - '0'
    - --key_range
    - '50'
    container_name: client3
    depends_on:
      node5:
        condition: service_started
    networks:
      raft-common-network:
        ipv4_address: 10.0.0.9
    ports:
    - 5562:8888/udp
    volumes:
    - ./dump:/app/dump
  client30:
    build: .
    command:
    - python
    - -m
    - evaluator.run_evaluator
    - --name
    - client30
    - --evaluator
    - cca
    - --duration
    - '7'
    - --requests_per_second
    - '130'
    - --write_ratio
    - '0'
    - --key_range
    - '50'
    container_name: client30
    depends_on:
      node5:
        condition: service_started
    networks:
      raft-common-network:
        ipv4_address: 10.0.0.36
    ports:
    - 5589:8888/udp
    volumes:
    - ./dump:/app/dump
  client31:
    build: .
    command:
    - python
    - -m
    - evaluator.run_evaluator
    - --name
    - client31
    - --evaluator
    - cca
    - --duration
    - '7'
    - --requests_per_second
    - '130'
    - --write_ratio
    - '0'
    - --key_range
    - '50'
    container_name: client31
    depends_on:
      node5:
        condition: service_started
    networks:
      raft-common-network:
        ipv4_address: 10.0.0.37
    ports:
    - 5590:8888/udp
    volumes:
    - ./dump:/app/dump
  client32:
    build: .
    command:
    - python
    - -m
    - evaluator.run_evaluator
    - --name
    - client32
    - --evaluator
    - cca
    - --duration
    - '7'
    - --requests_per_second
    - '130'
    - --write_ratio
    - '0'
    - --key_range
    - '50'
    container_name: client32
    depends_on:
      node5:
        condition: service_started
    networks:
      raft-common-network:
        ipv4_address: 10.0.0.38
    ports:
    - 5591:8888/udp
    volumes:
    - ./dump:/app/dump
  client4:
    build: .
    command:
    - python
    - -m
    - evaluator.run_evaluator
    - --name
    - client4
    - --evaluator
    - cca
    - --duration
    - '7'
    - --requests_per_second
    - '130'
    - --write_ratio
    - '0'
    - --key_range
    - '50'
    container_name: client4
    depends_on:
      node5:
        condition: service_started
    networks:
      raft-common-network:
        ipv4_address: 10.0.0.10
    ports:
    - 5563:8888/udp
    volumes:
    - ./dump:/app/dump
  client5:
    build: .
    command:
    - python
    - -m
    - evaluator.run_evaluator
    - --name
    - client5
    - --evaluator
    - cca
    - --duration
    - '7'
    - --requests_per_second
    - '130'
    - --write_ratio
    - '0'
    - --key_range
    - '50'
    container_name: client5
    depends_on:
      node5:
        condition: service_started
    networks:
      raft-common-network:
        ipv4_address: 10.0.0.11
    ports:
    - 5564:8888/udp
    volumes:
    - ./dump:/app/dump
  client6:
    build: .
    command:
    - python
    - -m
    - evaluator.run_evaluator
    - --name
    - client6
    - --evaluator
    - cca
    - --duration
    - '7'
    - --requests_per_second
    - '130'
    - --write_ratio
    - '0'
    - --key_range
    - '50'
    container_name: client6
    depends_on:
      node5:
        condition: service_started
    networks:
      raft-common-network:
        ipv4_address: 10.0.0.12
    ports:
    - 5565:8888/udp
    volumes:
    - ./dump:/app/dump
  client7:
    build: .
    command:
    - python
    - -m
    - evaluator.run_evaluator
    - --name
    - client7
    - --evaluator
    - cca
    - --duration
    - '7'
    - --requests_per_second
    - '130'
    - --write_ratio
    - '0'
    - --key_range
    - '50'
    container_name: client7
    depends_on:
      node5:
        condition: service_started
    networks:
      raft-common-network:
        ipv4_address: 10.0.0.13
    ports:
    - 5566:8888/udp
    volumes:
    - ./dump:/app/dump
  client8:
    build: .
    command:
    - python
    - -m
    - evaluator.run_evaluator
    - --name
    - client8
    - --evaluator
    - cca
    - --duration
    - '7'
    - --requests_per_second
    - '130'
    - --write_ratio
    - '0'
    - --key_range
    - '50'
    container_name: client8
    depends_on:
      node5:
        condition: service_started
    networks:
      raft-common-network:
        ipv4_address: 10.0.0.14
    ports:
    - 5567:8888/udp
    volumes:
    - ./dump:/app/dump
  client9:
    build: .
    command:
    - python
    - -m
    - evaluator.run_evaluator
    - --name
    - client9
    - --evaluator
    - cca
    - --duration
    - '7'
    - --requests_per_second
    - '130'
    - --write_ratio
    - '0'
    - --key_range
    - '50'
    container_name: client9
    depends_on:
      node5:
        condition: service_started
    networks:
      raft-common-network:
        ipv4_address: 10.0.0.15
    ports:
    - 5568:8888/udp
    volumes:
    - ./dump:/app/dump
  node1:
    build: .
    command:
    - python
    - -m
    - raft.run_node
    - --node
    - 10.0.0.2
    - --cluster
    - node2,node3,node4,node5
    - --name
    - node1
    - --clients
    - client1,client2,client3,client4,client5,client6,client7,client8,client9,client10,client11,client12,client13,client14,client15,client16,client17,client18,client19,client20,client21,client22,client23,client24,client25,client26,client27,client28,client29,client30,client31,client32
    - --state
    - cca
    - --duration
    - '7'
    container_name: node1
    environment:
    - NODE=node1
    - CLUSTER=node2,node3,node4,node5
    - CLIENTS=client1,client2,client3,client4,client5,client6,client7,client8,client9,client10,client11,client12,client13,client14,client15,client16,client17,client18,client19,client20,client21,client22,client23,client24,client25,client26,client27,client28,client29,client30,client31,client32
    networks:
      raft-common-network:
        ipv4_address: 10.0.0.2
    ports:
    - 3333:8080/udp
    volumes:
    - ./dump:/app/dump
  node2:
    build: .
    command:
    - python
    - -m
    - raft.run_node
    - --node
    - 10.0.0.3
    - --cluster
    - node1,node3,node4,node5
    - --name
    - node2
    - --clients
    - client1,client2,client3,client4,client5,client6,client7,client8,client9,client10,client11,client12,client13,client14,client15,client16,client17,client18,client19,client20,client21,client22,client23,client24,client25,client26,client27,client28,client29,client30,client31,client32
    - --state
    - cca
    - --duration
    - '7'
    container_name: node2
    environment:
    - NODE=node2
    - CLUSTER=node1,node3,node4,node5
    - CLIENTS=client1,client2,client3,client4,client5,client6,client7,client8,client9,client10,client11,client12,client13,client14,client15,client16,client17,client18,client19,client20,client21,client22,client23,client24,client25,client26,client27,client28,client29,client30,client31,client32
    networks:
      raft-common-network:
        ipv4_address: 10.0.0.3
    ports:
    - 3334:8080/udp
    volumes:
    - ./dump:/app/dump
  node3:
    build: .
    command:
    - python
    - -m
    - raft.run_node
    - --node
    - 10.0.0.4
    - --cluster
    - node1,node2,node4,node5
    - --name
    - node3
    - --clients
    - client1,client2,client3,client4,client5,client6,client7,client8,client9,client10,client11,client12,client13,client14,client15,client16,client17,client18,client19,client20,client21,client22,client23,client24,client25,client26,client27,client28,client29,client30,client31,client32
    - --state
    - cca
    - --duration
    - '7'
    container_name: node3
    environment:
    - NODE=node3
    - CLUSTER=node1,node2,node4,node5
    - CLIENTS=client1,client2,client3,client4,client5,client6,client7,client8,client9,client10,client11,client12,client13,client14,client15,client16,client17,client18,client19,client20,client21,client22,client23,client24,client25,client26,client27,client28,client29,client30,client31,client32
    networks:
      raft-common-network:
        ipv4_address: 10.0.0.4
    ports:
    - 3335:8080/udp
    volumes:
    - ./dump:/app/dump
  node4:
    build: .
    command:
    - python
    - -m
    - raft.run_node
    - --node
    - 10.0.0.5
    - --cluster
    - node1,node2,node3,node5
    - --name
    - node4
    - --clients
    - client1,client2,client3,client4,client5,client6,client7,client8,client9,client10,client11,client12,client13,client14,client15,client16,client17,client18,client19,client20,client21,client22,client23,client24,client25,client26,client27,client28,client29,client30,client31,client32
    - --state
    - cca
    - --duration
    - '7'
    container_name: node4
    environment:
    - NODE=node4
    - CLUSTER=node1,node2,node3,node5
    - CLIENTS=client1,client2,client3,client4,client5,client6,client7,client8,client9,client10,client11,client12,client13,client14,client15,client16,client17,client18,client19,client20,client21,client22,client23,client24,client25,client26,client27,client28,client29,client30,client31,client32
    networks:
      raft-common-network:
        ipv4_address: 10.0.0.5
    ports:
    - 3336:8080/udp
    volumes:
    - ./dump:/app/dump
  node5:
    build: .
    command:
    - python
    - -m
    - raft.run_node
    - --node
    - 10.0.0.6
    - --cluster
    - node1,node2,node3,node4
    - --name
    - node5
    - --clients
    - client1,client2,client3,client4,client5,client6,client7,client8,client9,client10,client11,client12,client13,client14,client15,client16,client17,client18,client19,client20,client21,client22,client23,client24,client25,client26,client27,client28,client29,client30,client31,client32
    - --state
    - cca
    - --duration
    - '7'
    container_name: node5
    environment:
    - NODE=node5
    - CLUSTER=node1,node2,node3,node4
    - CLIENTS=client1,client2,client3,client4,client5,client6,client7,client8,client9,client10,client11,client12,client13,client14,client15,client16,client17,client18,client19,client20,client21,client22,client23,client24,client25,client26,client27,client28,client29,client30,client31,client32
    networks:
      raft-common-network:
        ipv4_address: 10.0.0.6
    ports:
    - 3337:8080/udp
    volumes:
    - ./dump:/app/dump
version: '3.8'
